import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import project2 from "../assets/project2.png";
import BlogScreenShot from "../assets/BlogScreenShot.png";
import PomoTimer from "../assets/PomoTimer.png";
import FitSoc from "../assets/FitSocial.png";
import AiCoach from "../assets/AI_Interviewer.jpg";
import SoftMaxReg from "../assets/SoftMaxRegression.png";
import GameDev from "../assets/GameDev.MP4";
import DSoccer from "../assets/DSoccer.png";
import FigmaDesign from "../assets/FigmaDesign.png";
import Github from "../assets/Github.png";

const machineLearningProjects = [
  {
    id: 4,
    title: "Softmax Regression",
    img: SoftMaxReg,
    description:
      "Implementation of softmax regression from scratch using NumPy to classify handwritten digits from the MNIST dataset.",
    url: "https://colab.research.google.com/drive/15J1HV2gb4Zk5hib16md7PntMZRhq8F1S?usp=sharing"
  },
  {
    id: 5,
    title: "AI Interview Coach",
    img: AiCoach,
    description:
      "AI interview coach that provides real-time feedback on your answers, helping you improve your interview skills. More updates to come!",
    url: "https://ai-mock-interviews-teal.vercel.app/"
  },
  {
    id: 6,
    title: "LLM Project",
    img: project2,
    description: "Coming Soon",
  },
];

const webAppProjects = [
  {
    id: 1,
    title: "My Blog",
    img: BlogScreenShot,
    description:
      "Personal blog to take you along on my journey to greatness.",
    url: "https://seye-sblog.onrender.com/",
  },
  {
    id: 2,
    title: "Fit Social",
    img: FitSoc,
    description:
      "Fitness Social Media App coming soon. Ask to see a demo!",
    url: "https://fitsocial.fit",
  },
  {
    id: 3,
    title: " Pomodoro Timer",
    img: PomoTimer,
    description:
      "Simple Productivity Tool to help with focus and time management.",
    url: "https://seyespomodorotimer.netlify.app/",
  },
];

const githubRepos = [
  {
    id: 7,
    title: "Video Edge Detection Project",
    img: Github,
    description: "Using Python to process video frames and apply edge detection algorithms.",
    url: "https://github.com/seyeoyadiran/VideoEdgeDetection",
  },
  {
    id: 8,
    title: "Task Manager W/Spring Boot",
    img: Github,
    description: " Java project using Spring Boot backend with RESTful APIs for managing tasks.",
    url: "https://github.com/seyeoyadiran/TaskManager_withSpringBoot",
  },
  {
    id: 9,
    title: "Sustainable Foraging W/Spring Boot",
    img: Github,
    description: " A Spring-based Java console application for tracking, managing, and reporting foraging activities.",
    url: "https://github.com/seyeoyadiran/Sustainable_Foraging",
  },

];

const otherProjects = [
  {
    id: 10,
    title: "Durty Soccer",
    img: DSoccer,
    video: GameDev,
    description: "A fun, competitive 3D soccer game built with Unreal Engine. Click to watch preview.",
  },
  {
    id: 11, 
    title: "Restaurant Booking Figma Design",
    img: FigmaDesign,
    description: "Figma design prototype for a restaurant booking app. Click to view design.",
    url: "https://www.figma.com/proto/sLGU2jAkJwGxoeqnBLychw/EOC-----Project--Little-Lemon-book-a-table--Community-?node-id=1-36&t=9gqPSBNZqojbbprO-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A36"
  },

  {
    id: 12, 
    title: "MandelBrotSet",
    img: Github,
    description: "The Mandelbrot set is a fractal showing complex, infinitely detailed patterns generated by iterating a simple mathematical formula.",
    url: "https://colab.research.google.com/drive/1gkmszeSekdF4euoLv8YHLSSa_egD5v6M?usp=sharing"
  }
];

export default function Projects() {
  const [activeTab, setActiveTab] = useState("web");
  const [videoSrc, setVideoSrc] = useState(null);

  // ESC key to close modal
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape") setVideoSrc(null);
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  const getProjects = () => {
    switch (activeTab) {
      case "web":
        return webAppProjects;
      case "ml":
        return machineLearningProjects;
      case "github":
        return githubRepos;
      case "other":
        return otherProjects;
      default:
        return [];
    }
  };

  return (
    <section
      id="projects"
      className="py-12 md:py-20 px-4 md:px-6 text-white bg-blackLux/40 backdrop-blur-md border border-yellow-400/20 shadow-lg shadow-yellow-900/30 max-w-6xl mx-auto rounded-lg"
    >
      <motion.h2
        initial={{ opacity: 0, y: -30 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-2xl md:text-3xl font-bold border-b-4 border-yellow-500 inline-block pb-2 mb-8 md:mb-12 tracking-wide"
      >
        Projects
      </motion.h2>

      {/* Tabs */}
      <div className="flex flex-wrap justify-center gap-3 md:gap-6 mb-8 md:mb-12">
        {[
          
          { id: "web", label: "Web / App" },
          { id: "ml", label: "AI/Machine Learning" },
          { id: "github", label: "GitHub Repos" },
          { id: "other", label: "Other Projects" },
        ].map(({ id, label }) => (
          <button
            key={id}
            onClick={() => setActiveTab(id)}
            className={`px-4 md:px-5 py-2 rounded-full font-semibold text-sm md:text-base transition ${
              activeTab === id
                ? "bg-yellow-500 text-black shadow-lg"
                : "bg-gray-800 hover:bg-gray-700 text-yellow-400"
            }`}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Projects grid */}
      <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 md:gap-10">
        {getProjects().map((p) => (
          <motion.div
            key={p.id}
            whileHover={{ scale: 1.04 }}
            className={`relative group bg-blackLux/60 rounded-2xl overflow-hidden shadow-xl shadow-yellow-900/40 border border-yellow-700/40 cursor-pointer transition ${
              p.video && "hover:ring-2 hover:ring-yellow-400 hover:shadow-yellow-500"
            }`}
            onClick={() => {
              if (p.video) setVideoSrc(p.video);
              else if (p.url) window.open(p.url, "_blank");
            }}
          >
            <img src={p.img} alt={p.title} className="w-full h-52 object-cover rounded-t-2xl" />

            {/* Play Overlay for video items — always visible on touch, hover-only on desktop */}
            {p.video && (
              <div className="absolute inset-x-0 top-0 h-52 flex items-center justify-center transition md:bg-black/60 md:opacity-0 md:group-hover:opacity-100">
                <span className="text-yellow-400 text-base md:text-lg font-bold bg-black/50 px-3 py-1 rounded-full border border-yellow-400">
                  ▶ Play Preview
                </span>
              </div>
            )}

            <div className="p-5 md:p-6">
              <h3 className="text-xl md:text-2xl font-semibold text-yellow-400">{p.title}</h3>
              <p className="mt-3 text-sm md:text-base text-gray-300 leading-relaxed tracking-wide">{p.description}</p>
            </div>
          </motion.div>
        ))}
      </div>

      {/* 🎬 Video Modal */}
      <AnimatePresence>
        {videoSrc && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/70 backdrop-blur-sm flex justify-center items-center z-50 px-4"
            onClick={() => setVideoSrc(null)}
          >
            <motion.div
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.8, opacity: 0 }}
              transition={{ duration: 0.3 }}
              className="relative bg-blackLux border border-yellow-500/40 shadow-2xl rounded-xl overflow-hidden w-full"
              style={{ maxWidth: "600px" }}
              onClick={(e) => e.stopPropagation()}
            >
              <video
                src={videoSrc}
                controls
                autoPlay
                playsInline
                className="w-full max-h-[75vh] object-contain rounded-lg bg-black"
              />
              <button
                onClick={() => setVideoSrc(null)}
                aria-label="Close video"
                className="absolute top-2 right-3 text-white text-2xl font-bold p-1"
              >
                ✕
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}

